title: MTEAPY's homepage
description: Python library for Metabolic Task Enrichment Analysis using metabolic models
theme: jekyll-theme-cayman
show_downloads: true

github:
  zip_url: https://github.com/bsc-life/mteapy/zipball/main
  tar_url: https://github.com/bsc-life/mteapy/tarball/main