title: MTEApy
description: A Python library for Metabolic Task Enrichment Analysis
# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
repository: bsc-life/mteapy

aux_links_new_tab: true
aux_links:
  View MTEApy on GitHub:
    - https://github.com/bsc-life/mteapy
nav_links_new_tab: true
nav_external_links:
  - title: Download .tar.gz
    url: https://github.com/bsc-life/mteapy/tarball/main
  - title: View MTEApy on GitHub
    url: https://github.com/bsc-life/mteapy

footer_content: true
color_scheme: light

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
