title: MTEAPY's homepage
description: Python library for Metabolic Task Enrichment Analysis
theme: jekyll-theme-cayman
# remote_theme: zendesk/jekyll-theme-zendesk-garden@main
show_downloads: true

github:
  zip_url: https://github.com/bsc-life/mteapy/zipball/main
  tar_url: https://github.com/bsc-life/mteapy/tarball/main